homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.beranda, name='beranda'),
    path('tentang/', views.tentang, name='tentang'),
    path('kontak/', views.kontak, name='kontak'),
    path('pengalaman/', views.pengalaman, name='pengalaman'),
    path('galeri/', views.galeri, name='galeri'),
    path('kegiatan/', views.kegiatan, name = 'kegiatan'),
    path('tambah/', views.tambah_kegiatan, name = 'tambah'),
    path('pilih/<kegiatan_id>', views.pilih, name='pilih'),
    path('hapus/', views.hapusKegiatan, name='delete'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    namaKegiatan = models.CharField(max_length = 50)
    tanggalKegiatan = models.DateField()
    tempatKegiatan = models.CharField(max_length = 50)
    jamKegiatan = models.TimeField()
    kategoriKegiatan = models.CharField(max_length = 50)
    dipilih = models.BooleanField(default = False)
    
    def __str__(self):
        return self.namaKegiatan

homepage/forms.py
from django import forms

class Formnya(forms.Form):
    namaKegiatan = forms.CharField(max_length = 50,
                                   widget = forms.TextInput(attrs = {
                                       'class' : 'form-control',
                                       'placeholder' : 'ex : Tidur'}))
    tanggalKegiatan = forms.DateField(widget = forms.DateInput(attrs = {
                                        'class' : 'form=control',
                                        'placeholder' : '',
                                        'type':'date'}))
    tempatKegiatan = forms.CharField(max_length = 50,
                                   widget = forms.TextInput(attrs = {
                                       'class' : 'form-control',
                                       'placeholder' : 'ex : Kamar'}))
    jamKegiatan = forms.TimeField(widget = forms.TimeInput(attrs = {
                                        'class' : 'form-control',
                                        'type' : 'time'}))
    kategoriKegiatan = forms.CharField(max_length = 50,
                                   widget = forms.TextInput(attrs = {
                                       'class' : 'form-control',
                                       'placeholder' : 'ex : Istirahat'}))
    
    

homepage/views.py
from django.shortcuts import render, redirect
from .models import Kegiatan
from .forms import Formnya
from django.views.decorators.http import require_POST

def beranda(request):
    return render(request, 'Beranda.html')
def galeri(request):
    return render(request, 'Galeri.html')
def kontak(request):
    return render(request, 'Kontak.html')
def pengalaman(request):
    return render(request, 'Pengalaman.html')
def tentang(request):
    return render(request, 'Tentang.html')
def kegiatan(request):
    list_kegiatan = Kegiatan.objects.order_by('tanggalKegiatan')
    form = Formnya()
    context = {'list_kegiatan' : list_kegiatan, 'form' : form}
    return render(request, 'Kegiatan.html', context)
# Create your views here.

@require_POST
def tambah_kegiatan(request):
    form = Formnya(request.POST)
    if form.is_valid():
        kegiatan_baru = Kegiatan(namaKegiatan = request.POST['namaKegiatan'],
                                 tanggalKegiatan = request.POST['tanggalKegiatan'],
                                 tempatKegiatan = request.POST['tempatKegiatan'],
                                 jamKegiatan = request.POST['jamKegiatan'],
                                 kategoriKegiatan = request.POST['kategoriKegiatan'])
        
        kegiatan_baru.save()
    return redirect('homepage:kegiatan')

def pilih(request, kegiatan_id):
    kegiatan = Kegiatan.objects.get(pk = kegiatan_id)
    if kegiatan.dipilih == False:
        kegiatan.dipilih = True
    else:
        kegiatan.dipilih == False
    
    kegiatan.save()

    return redirect('homepage:kegiatan')

def hapusKegiatan(request):
    Kegiatan.objects.filter(dipilih__exact = True).delete()

    return redirect('homepage:kegiatan')

homepage/templates/Beranda.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/Style.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<style>
  
</style>
</head>
<body class="beranda">

	<nav style=background: class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'homepage:beranda' %}">Beranda <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:tentang' %}">Tentang</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:kontak' %}">Kontak</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:pengalaman' %}">Pengalaman</a>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:galeri' %}">Galeri</a>
       <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:kegiatan' %}">Kegiatan</a>
      </li>
    </ul>
  </div>
</nav>

<p id="tulisanberanda1">Halo Semua!</p>
<p id="tulisanberanda2">Saya Raihan Miftah</p>

</body>
</html>

homepage/templates/Galeri.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/Style.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<style>
  
</style>
</head>
<body style="background-color: darkgrey">

	<nav style=background: class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:beranda' %}">Beranda <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:tentang' %}">Tentang</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:kontak' %}">Kontak</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:pengalaman' %}">Pengalaman</a>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'homepage:galeri' %}">Galeri</a>
       <li class="nav-item">
         <a class="nav-link" href="{% url 'homepage:kegiatan' %}">Kegiatan</a>
        </li>
      </div>
    </ul>
</nav>

<img src="{% static 'images/depor.jpg' %}" id="fotodepor">
<img src="{% static 'images/runtime.png' %}" id="fotoruntime">

</body>
</html>

homepage/templates/Kegiatan.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/Style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<style>

</style>
</head>
<body style="background-color:darkgrey;">

  <nav style=background: class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:beranda' %}">Beranda <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:tentang' %}">Tentang</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:kontak' %}">Kontak</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:pengalaman' %}">Pengalaman</a>
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'homepage:galeri' %}">Galeri</a>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'homepage:kegiatan' %}">Kegiatan</a>
      </li>
    </ul>
  </div>
</nav>

<div class="container-fluid container-form" id="wrapper" style="padding-left: 5vw;margin-bottom: 3vw;">

    <div class="" id="content">
        <p>Kegiatan</p>

        <form action="{% url 'homepage:tambah' %}" method="POST" role="form">
            {% csrf_token %}
            <table>
                <tr>
                    <td>
                        <p style="font-size: 1.111vw;">Nama Kegiatan</p>
                    </td>
                    <td>
                        <div class="input-group" style="margin-left: 3vw;">
                            {{form.namaKegiatan}}
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p style="font-size: 1.111vw;">Tanggal</p>
                    </td>
                    <td>
                        <div class="input-group" style="margin-left: 3vw;">
                            {{form.tanggalKegiatan}}
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p style="font-size: 1.111vw;">Tempat</p>
                    </td>
                    <td>
                        <div class="input-group" style="margin-left: 3vw;">
                            {{form.tempatKegiatan}}
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p style="font-size: 1.111vw;">Jam</p>
                    </td>
                    <td>
                        <div class="input-group" style="margin-left: 3vw;">
                            {{form.jamKegiatan}}
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p style="font-size: 1.111vw;">Kategori</p>
                    </td>
                    <td>
                        <div class="input-group" style="margin-left: 3vw;">
                            {{form.kategoriKegiatan}}
                        </div>
                    </td>
                </tr>
            </table>

            <span class="input-group-btn">
                <button type="submit" class="btn" id="add-btn">ADD</button>
            </span>
        </form>
        <ul class="list-group t20" style="margin-right: 40vw; margin-top: 3vw; font-size:1.111vw;">
            <table>
                <tr>
                    <td>
                        <li class="list-group-item">Kegiatan</li>
                    </td>
                    <td>
                        <li class="list-group-item">Tanggal</li>
                    </td>
                    <td>
                        <li class="list-group-item">Tempat</li>
                    </td>
                    <td>
                        <li class="list-group-item">Jam</li>
                    </td>
                    <td>
                        <li class="list-group-item">Kategori</li>
                    </td>
                </tr>
            </table>
            {% for kegiatan in list_kegiatan %}
            <table>
                <tr>
                    <td>
                        <li class="list-group-item">{{ kegiatan.namaKegiatan }}</li>
                    </td>
                    <td>
                        <li class="list-group-item">{{ kegiatan.tanggalKegiatan }}</li>
                    </td>
                    <td>
                        <li class="list-group-item">{{ kegiatan.tempatKegiatan }}</li>
                    </td>
                    <td>
                        <li class="list-group-item">{{ kegiatan.jamKegiatan }}</li>
                    </td>
                    <td>
                        <li class="list-group-item">{{ kegiatan.kategoriKegiatan }}</li>
                    </td>

                    <td>
                        {% if kegiatan.dipilih %}
                        <a href="{% url 'homepage:pilih' kegiatan.id %}">
                            <button class="btn" >
                            </button>
                        </a>

                        {% else %}
                        <a href="{% url 'homepage:pilih' kegiatan.id %}">
                            <button class="btn" style="background-color: #ededed;">
                            </button>
                        </a>
                        {% endif %}
                    </td>
                </tr>
            </table>
            {% endfor %}
            <a href="{% url 'homepage:delete' %}" style="margin-top: 3vw;"><span class="input-group-btn">
                    <button type="button" class="btn" id="add-btn">Delete</button>
                </span></a>
        </ul>
    </div>

</div>


</body>
</html>

homepage/templates/Kontak.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/Style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<style>
  
</style>
</head>
<body style="background-color:darkgrey;">

  <nav style=background: class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:beranda' %}">Beranda <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:tentang' %}">Tentang</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'homepage:kontak' %}">Kontak</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:pengalaman' %}">Pengalaman</a>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:galeri' %}">Galeri</a>
       <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:kegiatan' %}">Kegiatan</a>
      </li>
    </ul>
  </div>
</nav>

<div>
    <img src = "{% static 'images/foto-kontak.png' %}" id="fotoprofil"/>
    <a href="https://twitter.com/raihanmiftah"><img src = "{% static 'images/Twitter.png' %}" id="fototwitter"/></a>
    <a href="https://www.facebook.com/miftah.reyhan"><img src = "{% static 'images/Facebook.png' %}" id="fotofacebook"/></a>
    <a href="https://www.instagram.com/raihanmiftah/"><img src = "{% static 'images/Instagram.png' %}" id="fotoinstagram"/></a>
    <img src = "{% static 'images/Contact.png' %}" id="fotocontact"/>
</div>



</body>
</html>

homepage/templates/Pengalaman.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/Style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<style>
</style>
</head>
<body style="background-color:darkgrey;">

<nav style=background: class="navbar navbar-expand-lg navbar-dark bg-dark">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:beranda' %}">Beranda <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:tentang' %}">Tentang</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:kontak' %}">Kontak</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'homepage:pengalaman' %}">Pengalaman</a>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:galeri' %}">Galeri</a>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:kegiatan' %}">Kegiatan</a>
      </li>
    </ul>
  </div>
</nav>

<div id="tulisanpengalaman">
  <br>&nbsp;&nbsp;&nbsp;&nbsp; Pengalaman Organisasi
    <img src="{% static 'images/Organisasi.png' %}" id="fotopengalaman">
</div>
</body>
</html>

homepage/templates/Tentang.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/Style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<style>

</style>
</head>
<body style="background-color:darkgrey;">

  <nav style=background: class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:beranda' %}">Beranda <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'homepage:tentang' %}">Tentang</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:kontak' %}">Kontak</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:pengalaman' %}">Pengalaman</a>
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'homepage:galeri' %}">Galeri</a>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:kegiatan' %}">Kegiatan</a>
      </li>
    </ul>
  </div>
</nav>

<img src="{% static 'images/foto-tentang.png' %}" id="fototentang">

<div id="tulisantentang">
    Saya merupakan anak ketiga dari tiga bersaudara yang lahir di Depok pada <br>tanggal 11 April 2001. Saya saat ini sedang berjuang keras dalam dunia <br>perkuliahan di Fakultas Ilmu Komputer Universitas Indonesia. Di Fasilkom ini <br>saya mengikuti beberapa kegiatan organisasi dan kepanitiaan seperti BEM <br>Fasilkom Departemen Olahraga sebagai Staff dan telah menyelesaikan <br>kepanitiaan CSL (Computer Science League) sebagai Staff.
</div>

</body>
</html>